# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту mailto:youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - serdg1984@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
# Разворачиваем базу данных

env:
  global:
    - CODECOV_TOKEN="b9c42815-b0d2-4be3-aa81-5b25225ca24e"
jdk:
  - openjdk11

services:
  - postgresql
before_install:
- psql -c 'create database car_storage;' -U postgres